# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  deploy:  
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write  
    env:
      package_version: 0.1.0
      configuration: Release
      NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

    steps:
    - uses: actions/checkout@v3    
    - uses: nuget/setup-nuget@v1
      with:
        dotnet-version: 7.0.x
        source-url: 'https://nuget.pkg.github.com/{{ github.repository_owner }}/index.json'
        
    - name: Restore dependencies
      run: dotnet restore --configuration {{ env.configuration }}

    - name: Build
      run: dotnet build --configuration {{ env.configuration }} --no-restore
      
    - name: Publish
      run: dotnet nuget push "**/*.nupkg"
