# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
  
    env:
      BUILD_CONFIG: 'Release'
      Solution: 'PrivateNuget.sln'

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
   
    - name: Setup NuGet
      uses: Nuget/setup-nuget@v1.0.5

    - name: Restore dependencies
      run: dotnet restore $SOLUTION

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
     
    - name: Build
      run: dotnet build $SOLUTION --configuration $BUILD_CONFIG --no-restore
      
    - name: Publish
      #if: startsWith(github.ref, 'refs/heads/release')
      #run: nuget push "**\*.nupkg" --source "github" --SkipDuplicated
      
      run: dotnet nuget push "**/*.nupkg" --source https://api.nuget.org/v3/index.json --skip-duplicate
      
    #- name: Test
    #  run: dotnet test /p:Configuration=$env:BUILD_CONFIG --no-restore --no-build --verbosity normal
